---
title: Connor Montgomery
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  projects:
    title: Projects
    output: true
    permalink: "/project/:title/"
  uploads:
    title: Uploads
    output: true
author: Connor Montgomery
email: c@cnnr.me
description: I'm a product-driven software engineer living in Kansas City. High five!
url: https://connor.github.io
google_analytics: UA-169330673-1
exclude:
- README.md
- CNAME
twitter:
  username: connor
social:
  name: Connor Montgomery
  links:
  - https://twitter.com/connor
  - https://github.com/connor
  - https://pinterest.com/cnnr
  - https://www.linkedin.com/in/connormontgomery/
github:
  repository_url: https://github.com/connor/connor.github.io
theme: minima
plugins:
- jekyll-feed
permalink: "/blog/:title/"
